# Import pandas

In [2]:
import pandas as pd

# Create pandas dataframe

In [5]:
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Price': [999.99, 24.99, 79.99, 349.99, 149.99],
    'Stock': [15, 150, 75, 30, 60],
    'Rating': [4.5, 4.2, 4.7, 4.4, 4.6]
}

In [ ]:
df = pd.DataFrame(data)
df

      Product     Category   Price  Stock  Rating
0      Laptop  Electronics  999.99     15     4.5
1       Mouse  Electronics   24.99    150     4.2
2    Keyboard  Electronics   79.99     75     4.7
3     Monitor  Electronics  349.99     30     4.4
4  Headphones  Electronics  149.99     60     4.6

In [8]:
df.shape

(5, 5)

In [14]:
df_columns = df.columns.tolist()
df_columns

['Product', 'Category', 'Price', 'Stock', 'Rating']

In [15]:
df.dtypes

Product      object
Category     object
Price       float64
Stock         int64
Rating      float64
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   5 non-null      object
 1   Category  5 non-null      object
 2   Price     5 non-null      float64
 3   Stock     5 non-null      int64
 4   Rating    5 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 328.0+ bytes

# Reading Data from Files

In [24]:
df_sales = pd.read_csv("../datasets/sales_data.csv")
df_sales.head(20)

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
0,TXN000789,2024-01-01,PRD008,CUST0185,5,67.02,North,David Lee,Credit Card,335.10
1,TXN000385,2024-01-01,PRD011,CUST0130,4,15.69,West,Lisa Martinez,Debit Card,62.76
2,TXN000408,2024-01-01,PRD049,CUST0164,8,181.81,South,Lisa Martinez,Credit Card,1454.48
3,TXN000128,2024-01-01,PRD031,CUST0142,7,426.11,West,Mary Johnson,Cash,2982.77
4,TXN000838,2024-01-02,PRD043,CUST0173,1,350.57,Central,John Smith,Credit Card,350.57
5,TXN000307,2024-01-02,PRD044,CUST0123,7,347.06,West,Robert Garcia,Cash,2429.42
6,TXN000116,2024-01-02,PRD033,CUST0187,7,54.88,East,David Lee,Cash,384.16
7,TXN000223,2024-01-02,PRD007,CUST0029,6,443.06,North,Michael Brown,Cash,2658.36
8,TXN000714,2024-01-02,PRD006,CUST0049,6,61.01,North,Robert Garcia,Credit Card,366.06
9,TXN000444,2024-01-03,PRD029,CUST0079,7,117.41,South,Michael Brown,Debit Card,821.87
10,TXN000165,2024-01-04,PRD047,CUST0156,1,444.13,South,Robert Garcia,Debit Card,444.13
11,TXN000499,2024-01-04,PRD042,CUST0114,4,186.02,North,Michael Brown,Wire Transfer,744.08
12,TXN000022,2024-01-04,PRD048,CUST0147,6,23.00,South,Mary Johnson,Debit Card,138.00
13,TXN000314,2024-01-05,PRD015,CUST0070,4,314.25,East,Mary Johnson,Debit Card,1257.00
14,TXN000945,2024-01-05,PRD046,CUST0163,6,325.51,South,John Smith,Cash,1953.06
15,TXN000285,2024-01-05,PRD040,CUST0185,4,88.77,East,Jennifer Davis,PayPal,355.08
16,TXN000268,2024-01-05,PRD025,CUST0064,1,332.64,West,Mary Johnson,Cash,332.64
17,TXN000921,2024-01-05,PRD045,CUST0099,8,478.69,West,Robert Garcia,Debit Card,3829.52
18,TXN000107,2024-01-06,PRD005,CUST0173,7,347.32,Central,Robert Garcia,Cash,2431.24
19,TXN000616,2024-01-06,PRD017,CUST0194,6,337.42,Central,Sarah Wilson,Credit Card,2024.52

In [25]:
# count missing valeus
df_sales.isnull().sum()

transaction_id    0
date              0
product_id        0
customer_id       0
quantity          0
unit_price        0
region            0
sales_rep         0
payment_method    0
total_amount      0
dtype: int64

In [21]:
df_sales.columns.tolist()

['transaction_id',
 'date',
 'product_id',
 'customer_id',
 'quantity',
 'unit_price',
 'region',
 'sales_rep',
 'payment_method',
 'total_amount']

# Selecting Columns

In [28]:
df_sales['date']

0      2024-01-01
1      2024-01-01
2      2024-01-01
3      2024-01-01
4      2024-01-02
          ...
995    2024-09-25
996    2024-09-26
997    2024-09-27
998    2024-09-27
999    2024-09-27
Name: date, Length: 1000, dtype: object

In [29]:
df_sales[[
    'transaction_id',
    'date',
    'total_amount'
]]

    transaction_id        date  total_amount
0        TXN000789  2024-01-01        335.10
1        TXN000385  2024-01-01         62.76
2        TXN000408  2024-01-01       1454.48
3        TXN000128  2024-01-01       2982.77
4        TXN000838  2024-01-02        350.57
..             ...         ...           ...
995      TXN000654  2024-09-25        430.77
996      TXN000869  2024-09-26        382.54
997      TXN000147  2024-09-27       1729.60
998      TXN000105  2024-09-27       1834.05
999      TXN000284  2024-09-27        374.32

[1000 rows x 3 columns]

In [30]:
sales_renamed = df_sales.rename(columns={
    'total_amount': 'Total_Sales',
    'unit_price': 'Price_Per_Unit'
})

# Filtering Data

In [44]:
# Filter: Sales above $1000
df_sales[df_sales['total_amount']>1000]

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
2,TXN000408,2024-01-01,PRD049,CUST0164,8,181.81,South,Lisa Martinez,Credit Card,1454.48
3,TXN000128,2024-01-01,PRD031,CUST0142,7,426.11,West,Mary Johnson,Cash,2982.77
5,TXN000307,2024-01-02,PRD044,CUST0123,7,347.06,West,Robert Garcia,Cash,2429.42
7,TXN000223,2024-01-02,PRD007,CUST0029,6,443.06,North,Michael Brown,Cash,2658.36
13,TXN000314,2024-01-05,PRD015,CUST0070,4,314.25,East,Mary Johnson,Debit Card,1257.00
...,...,...,...,...,...,...,...,...,...,...
987,TXN000761,2024-09-22,PRD005,CUST0185,6,274.58,East,Robert Garcia,Cash,1647.48
988,TXN000794,2024-09-22,PRD029,CUST0165,4,404.90,Central,Jennifer Davis,PayPal,1619.60
992,TXN000590,2024-09-24,PRD019,CUST0029,6,393.37,South,Sarah Wilson,Debit Card,2360.22
997,TXN000147,2024-09-27,PRD036,CUST0094,4,432.40,North,Mary Johnson,Debit Card,1729.60
998,TXN000105,2024-09-27,PRD008,CUST0153,5,366.81,North,Lisa Martinez,Debit Card,1834.05

In [46]:
# Filter: Sales from the North region
df_sales[df_sales['region'] == 'North']

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
0,TXN000789,2024-01-01,PRD008,CUST0185,5,67.02,North,David Lee,Credit Card,335.10
7,TXN000223,2024-01-02,PRD007,CUST0029,6,443.06,North,Michael Brown,Cash,2658.36
8,TXN000714,2024-01-02,PRD006,CUST0049,6,61.01,North,Robert Garcia,Credit Card,366.06
11,TXN000499,2024-01-04,PRD042,CUST0114,4,186.02,North,Michael Brown,Wire Transfer,744.08
20,TXN000580,2024-01-07,PRD047,CUST0098,2,332.85,North,John Smith,Debit Card,665.70
...,...,...,...,...,...,...,...,...,...,...
981,TXN000378,2024-09-18,PRD026,CUST0073,7,250.88,North,John Smith,Credit Card,1756.16
989,TXN000449,2024-09-22,PRD005,CUST0181,1,332.77,North,Lisa Martinez,Debit Card,332.77
993,TXN000255,2024-09-24,PRD010,CUST0088,1,344.80,North,Robert Garcia,Credit Card,344.80
997,TXN000147,2024-09-27,PRD036,CUST0094,4,432.40,North,Mary Johnson,Debit Card,1729.60
998,TXN000105,2024-09-27,PRD008,CUST0153,5,366.81,North,Lisa Martinez,Debit Card,1834.05

In [ ]:
# Filter: AND condition
df_sales[(df_sales['region'] == 'North') & (df_sales['total_amount']>500)]

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
7,TXN000223,2024-01-02,PRD007,CUST0029,6,443.06,North,Michael Brown,Cash,2658.36
11,TXN000499,2024-01-04,PRD042,CUST0114,4,186.02,North,Michael Brown,Wire Transfer,744.08
20,TXN000580,2024-01-07,PRD047,CUST0098,2,332.85,North,John Smith,Debit Card,665.70
21,TXN000672,2024-01-07,PRD014,CUST0119,2,304.79,North,David Lee,Cash,609.58
45,TXN000806,2024-01-15,PRD028,CUST0060,2,432.39,North,Lisa Martinez,Cash,864.78
...,...,...,...,...,...,...,...,...,...,...
950,TXN000746,2024-09-09,PRD009,CUST0082,4,348.10,North,Jennifer Davis,Debit Card,1392.40
979,TXN000364,2024-09-17,PRD011,CUST0046,7,423.94,North,Sarah Wilson,Credit Card,2967.58
981,TXN000378,2024-09-18,PRD026,CUST0073,7,250.88,North,John Smith,Credit Card,1756.16
997,TXN000147,2024-09-27,PRD036,CUST0094,4,432.40,North,Mary Johnson,Debit Card,1729.60
998,TXN000105,2024-09-27,PRD008,CUST0153,5,366.81,North,Lisa Martinez,Debit Card,1834.05

In [48]:
# Filter: OR condition
df_sales[(df_sales['region'] == 'North') | (df_sales['total_amount']>500)]

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
0,TXN000789,2024-01-01,PRD008,CUST0185,5,67.02,North,David Lee,Credit Card,335.10
2,TXN000408,2024-01-01,PRD049,CUST0164,8,181.81,South,Lisa Martinez,Credit Card,1454.48
3,TXN000128,2024-01-01,PRD031,CUST0142,7,426.11,West,Mary Johnson,Cash,2982.77
5,TXN000307,2024-01-02,PRD044,CUST0123,7,347.06,West,Robert Garcia,Cash,2429.42
7,TXN000223,2024-01-02,PRD007,CUST0029,6,443.06,North,Michael Brown,Cash,2658.36
...,...,...,...,...,...,...,...,...,...,...
990,TXN000468,2024-09-23,PRD033,CUST0180,4,191.81,East,John Smith,Credit Card,767.24
992,TXN000590,2024-09-24,PRD019,CUST0029,6,393.37,South,Sarah Wilson,Debit Card,2360.22
993,TXN000255,2024-09-24,PRD010,CUST0088,1,344.80,North,Robert Garcia,Credit Card,344.80
997,TXN000147,2024-09-27,PRD036,CUST0094,4,432.40,North,Mary Johnson,Debit Card,1729.60
998,TXN000105,2024-09-27,PRD008,CUST0153,5,366.81,North,Lisa Martinez,Debit Card,1834.05

In [50]:
# Filter: Sales from the North region
df_sales[df_sales['region'].isin(['North', 'South'])]

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
0,TXN000789,2024-01-01,PRD008,CUST0185,5,67.02,North,David Lee,Credit Card,335.10
2,TXN000408,2024-01-01,PRD049,CUST0164,8,181.81,South,Lisa Martinez,Credit Card,1454.48
7,TXN000223,2024-01-02,PRD007,CUST0029,6,443.06,North,Michael Brown,Cash,2658.36
8,TXN000714,2024-01-02,PRD006,CUST0049,6,61.01,North,Robert Garcia,Credit Card,366.06
9,TXN000444,2024-01-03,PRD029,CUST0079,7,117.41,South,Michael Brown,Debit Card,821.87
...,...,...,...,...,...,...,...,...,...,...
993,TXN000255,2024-09-24,PRD010,CUST0088,1,344.80,North,Robert Garcia,Credit Card,344.80
994,TXN000696,2024-09-24,PRD002,CUST0173,8,56.90,South,John Smith,Wire Transfer,455.20
996,TXN000869,2024-09-26,PRD049,CUST0104,1,382.54,South,John Smith,Credit Card,382.54
997,TXN000147,2024-09-27,PRD036,CUST0094,4,432.40,North,Mary Johnson,Debit Card,1729.60
998,TXN000105,2024-09-27,PRD008,CUST0153,5,366.81,North,Lisa Martinez,Debit Card,1834.05

# Sorting Data

In [53]:
df_sales.sort_values(by='total_amount', ascending=True)

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
650,TXN000604,2024-06-21,PRD030,CUST0154,1,12.82,South,David Lee,Credit Card,12.82
964,TXN000864,2024-09-14,PRD044,CUST0168,1,15.41,South,David Lee,Wire Transfer,15.41
396,TXN000019,2024-04-22,PRD030,CUST0167,2,16.37,Central,John Smith,Debit Card,32.74
538,TXN000534,2024-05-22,PRD043,CUST0017,1,37.97,North,David Lee,Credit Card,37.97
703,TXN000057,2024-07-08,PRD006,CUST0034,2,19.01,Central,John Smith,Debit Card,38.02
...,...,...,...,...,...,...,...,...,...,...
88,TXN000540,2024-01-27,PRD042,CUST0074,9,467.60,East,David Lee,PayPal,4208.40
878,TXN000038,2024-08-23,PRD045,CUST0117,9,474.74,East,Mary Johnson,Credit Card,4272.66
194,TXN000445,2024-02-24,PRD003,CUST0041,9,488.17,North,Sarah Wilson,Credit Card,4393.53
208,TXN000132,2024-02-27,PRD007,CUST0130,9,493.96,Central,John Smith,Wire Transfer,4445.64
654,TXN000195,2024-06-22,PRD009,CUST0177,9,493.98,West,Jennifer Davis,Cash,4445.82

In [55]:
df_sales.sort_values(by=['payment_method','total_amount'], ascending=True)

,transaction_id,date,product_id,customer_id,quantity,unit_price,region,sales_rep,payment_method,total_amount
838,TXN000867,2024-08-13,PRD024,CUST0009,2,19.40,South,Michael Brown,Cash,38.80
715,TXN000697,2024-07-13,PRD041,CUST0155,2,21.58,West,Sarah Wilson,Cash,43.16
589,TXN000409,2024-06-04,PRD042,CUST0104,2,26.27,North,Michael Brown,Cash,52.54
113,TXN000247,2024-02-04,PRD018,CUST0170,1,52.62,South,Jennifer Davis,Cash,52.62
834,TXN000154,2024-08-12,PRD030,CUST0129,1,69.08,West,Mary Johnson,Cash,69.08
...,...,...,...,...,...,...,...,...,...,...
62,TXN000372,2024-01-20,PRD016,CUST0003,9,245.95,West,Sarah Wilson,Wire Transfer,2213.55
413,TXN000071,2024-04-27,PRD049,CUST0025,9,304.25,West,Mary Johnson,Wire Transfer,2738.25
195,TXN000291,2024-02-24,PRD043,CUST0140,9,312.29,North,Sarah Wilson,Wire Transfer,2810.61
637,TXN000359,2024-06-17,PRD019,CUST0190,6,484.41,Central,Michael Brown,Wire Transfer,2906.46
208,TXN000132,2024-02-27,PRD007,CUST0130,9,493.96,Central,John Smith,Wire Transfer,4445.64

# Basic Calculations

In [58]:
# total sales
total_sales = df_sales['total_amount'].sum()
total_sales

np.float64(1246787.04)

In [65]:
df_sales['payment_method'].unique()
# df_sales['payment_method'].nunique()
df_sales['payment_method'].value_counts()
df_sales['payment_method'].value_counts(normalize=True)

payment_method
Credit Card      0.386
Debit Card       0.264
Cash             0.204
PayPal           0.112
Wire Transfer    0.034
Name: proportion, dtype: float64

# Adding new columns

In [69]:
df_sales['discount_10pct'] = df_sales['total_amount']*0.1
df_sales['amount_after_discount'] = df_sales['total_amount'] - df_sales['discount_10pct']
df_sales['amount_after_discount']

0       301.590
1        56.484
2      1309.032
3      2684.493
4       315.513
         ...
995     387.693
996     344.286
997    1556.640
998    1650.645
999     336.888
Name: amount_after_discount, Length: 1000, dtype: float64

# Working with dates

In [80]:
df_sales['date'] = pd.to_datetime(df_sales['date'])
df_sales['year'] = df_sales['date'].dt.year
df_sales['month'] = df_sales['date'].dt.month
df_sales['day'] = df_sales['date'].dt.day
df_sales['day_of_week'] = df_sales['date'].dt.day_name()
df_sales[['date','year','month','day','day_of_week']]

          date  year  month  day day_of_week
0   2024-01-01  2024      1    1      Monday
1   2024-01-01  2024      1    1      Monday
2   2024-01-01  2024      1    1      Monday
3   2024-01-01  2024      1    1      Monday
4   2024-01-02  2024      1    2     Tuesday
..         ...   ...    ...  ...         ...
995 2024-09-25  2024      9   25   Wednesday
996 2024-09-26  2024      9   26    Thursday
997 2024-09-27  2024      9   27      Friday
998 2024-09-27  2024      9   27      Friday
999 2024-09-27  2024      9   27      Friday

[1000 rows x 5 columns]

# Practice Exercise: Customer data analysis

In [3]:
import pandas as pd
df_customers = pd.read_csv("../datasets/customer_data.csv")

In [4]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       200 non-null    object
 1   first_name        200 non-null    object
 2   last_name         200 non-null    object
 3   email             200 non-null    object
 4   phone             200 non-null    object
 5   city              200 non-null    object
 6   state             200 non-null    object
 7   signup_date       200 non-null    object
 8   customer_segment  200 non-null    object
 9   total_purchases   200 non-null    int64
 10  lifetime_value    200 non-null    float64
dtypes: float64(1), int64(1), object(9)
memory usage: 17.3+ KB

In [14]:
# Exercise 1: Find premium customers
df_customers[df_customers['customer_segment'].str.lower() == 'premium']

,customer_id,first_name,last_name,email,phone,city,state,signup_date,customer_segment,total_purchases,lifetime_value
5,CUST0006,Elizabeth,Garcia,susan.gonzalez@email.com,(525) 663-5455,San Jose,CA,2023-03-02,Premium,17,4193.81
9,CUST0010,Lisa,Anderson,lisa.rodriguez@email.com,(660) 677-6145,New York,PA,2023-10-28,Premium,30,9540.96
12,CUST0013,Charles,Lee,david.jackson@email.com,(662) 515-8591,New York,NY,2022-03-17,Premium,21,1873.04
14,CUST0015,Jennifer,Garcia,lisa.anderson@email.com,(361) 902-5984,Los Angeles,TX,2023-03-24,Premium,35,9483.02
20,CUST0021,Elizabeth,Martin,jessica.rodriguez@email.com,(466) 378-1509,Chicago,PA,2023-06-23,Premium,16,7774.82
21,CUST0022,William,Miller,david.martinez@email.com,(614) 663-5093,Chicago,CA,2023-08-01,Premium,2,3491.65
31,CUST0032,John,White,james.wilson@email.com,(325) 243-8552,Philadelphia,FL,2023-12-06,Premium,5,3414.41
33,CUST0034,William,Jackson,robert.lee@email.com,(941) 604-9128,Philadelphia,NC,2022-08-10,Premium,20,6392.89
40,CUST0041,Michael,Anderson,mary.gonzalez@email.com,(621) 763-8848,San Diego,AZ,2022-05-14,Premium,42,2047.21
41,CUST0042,Joseph,Brown,christopher.martinez@email.com,(262) 289-5583,San Jose,GA,2022-01-06,Premium,2,2451.08
42,CUST0043,Patricia,Rodriguez,lisa.white@email.com,(592) 340-7868,San Jose,FL,2022-05-26,Premium,9,3068.99
48,CUST0049,Karen,Martin,robert.jackson@email.com,(529) 597-5430,San Diego,IL,2022-07-03,Premium,34,2120.47
53,CUST0054,Susan,Brown,patricia.wilson@email.com,(985) 798-4813,San Jose,OH,2022-07-31,Premium,18,8848.47
54,CUST0055,Christopher,Lopez,daniel.jones@email.com,(363) 302-5060,San Jose,OH,2023-02-28,Premium,7,3495.00
65,CUST0066,Richard,Thompson,karen.lee@email.com,(702) 238-2478,San Diego,NC,2023-06-28,Premium,33,3049.97
70,CUST0071,Christopher,Martinez,nancy.anderson@email.com,(531) 260-1359,San Antonio,PA,2023-05-19,Premium,6,1320.15
89,CUST0090,Joseph,Lee,mary.davis@email.com,(555) 527-3750,New York,NC,2022-09-05,Premium,30,7405.48
102,CUST0103,Linda,Smith,john.smith@email.com,(526) 467-2715,New York,NY,2023-01-16,Premium,46,4941.58
109,CUST0110,John,Lee,daniel.gonzalez@email.com,(360) 254-2659,Dallas,PA,2023-10-11,Premium,9,4393.57
113,CUST0114,Charles,Thomas,william.williams@email.com,(504) 443-2571,Phoenix,NC,2023-07-04,Premium,6,9415.82
115,CUST0116,Sarah,White,thomas.miller@email.com,(357) 255-6911,Houston,PA,2022-03-23,Premium,24,7442.11
124,CUST0125,Karen,Johnson,john.wilson@email.com,(596) 389-7078,Los Angeles,FL,2022-08-18,Premium,7,3634.13
132,CUST0133,Jennifer,Thomas,daniel.smith@email.com,(766) 262-7342,Philadelphia,NC,2022-10-19,Premium,20,4877.75
136,CUST0137,Charles,Jackson,jennifer.lopez@email.com,(604) 931-1568,Phoenix,PA,2023-11-24,Premium,34,9575.63
145,CUST0146,Patricia,Miller,joseph.taylor@email.com,(944) 268-2425,San Antonio,TX,2022-02-08,Premium,23,2139.20
151,CUST0152,Sarah,Johnson,nancy.brown@email.com,(353) 351-2641,Chicago,IL,2023-01-14,Premium,19,8407.09
152,CUST0153,Charles,Anderson,linda.taylor@email.com,(308) 776-2654,Houston,OH,2023-02-16,Premium,44,5551.54
157,CUST0158,Barbara,Brown,robert.garcia@email.com,(612) 347-7581,Chicago,IL,2022-05-09,Premium,29,7720.49
160,CUST0161,Nancy,Jackson,susan.davis@email.com,(963) 686-5400,New York,FL,2023-10-27,Premium,1,3482.25
168,CUST0169,Patricia,Martin,thomas.johnson@email.com,(392) 652-4463,Houston,NY,2023-01-21,Premium,16,3996.99
175,CUST0176,Barbara,Moore,elizabeth.jackson@email.com,(397) 405-1944,San Jose,FL,2023-06-23,Premium,23,8490.72
178,CUST0179,Joseph,Moore,barbara.jackson@email.com,(480) 577-8605,Philadelphia,NC,2023-12-13,Premium,7,1738.45
188,CUST0189,Joseph,Brown,richard.martinez@email.com,(893) 411-5408,San Jose,CA,2022-12-22,Premium,7,6702.58
189,CUST0190,David,Jones,patricia.miller@email.com,(867) 619-9409,New York,TX,2022-01-03,Premium,32,4410.42

In [16]:
df_customers.sort_values(by='lifetime_value', ascending=False).head(10)

,customer_id,first_name,last_name,email,phone,city,state,signup_date,customer_segment,total_purchases,lifetime_value
18,CUST0019,Robert,Gonzalez,richard.miller@email.com,(564) 605-9412,Chicago,CA,2022-03-05,Standard,43,9814.45
148,CUST0149,Thomas,Lee,jennifer.lopez@email.com,(732) 669-1202,Chicago,GA,2023-04-22,Standard,46,9775.11
158,CUST0159,Richard,Davis,mary.moore@email.com,(239) 605-6431,Houston,OH,2023-02-22,Basic,6,9756.56
134,CUST0135,Karen,Taylor,barbara.taylor@email.com,(903) 686-4860,New York,IL,2022-12-05,Basic,41,9675.98
74,CUST0075,David,White,lisa.gonzalez@email.com,(921) 878-7481,San Jose,OH,2022-10-28,Standard,42,9661.74
100,CUST0101,Christopher,Johnson,jessica.williams@email.com,(366) 662-2207,Philadelphia,OH,2023-08-14,Standard,1,9619.35
136,CUST0137,Charles,Jackson,jennifer.lopez@email.com,(604) 931-1568,Phoenix,PA,2023-11-24,Premium,34,9575.63
8,CUST0009,John,Wilson,richard.taylor@email.com,(359) 308-3693,Chicago,CA,2022-08-26,Basic,25,9560.93
9,CUST0010,Lisa,Anderson,lisa.rodriguez@email.com,(660) 677-6145,New York,PA,2023-10-28,Premium,30,9540.96
190,CUST0191,John,Wilson,thomas.davis@email.com,(220) 999-1145,San Jose,PA,2022-03-06,Standard,19,9535.89

In [21]:
df_reset = df_customers.nlargest(10, 'lifetime_value').reset_index(drop=True)
df_reset

,customer_id,first_name,last_name,email,phone,city,state,signup_date,customer_segment,total_purchases,lifetime_value
0,CUST0019,Robert,Gonzalez,richard.miller@email.com,(564) 605-9412,Chicago,CA,2022-03-05,Standard,43,9814.45
1,CUST0149,Thomas,Lee,jennifer.lopez@email.com,(732) 669-1202,Chicago,GA,2023-04-22,Standard,46,9775.11
2,CUST0159,Richard,Davis,mary.moore@email.com,(239) 605-6431,Houston,OH,2023-02-22,Basic,6,9756.56
3,CUST0135,Karen,Taylor,barbara.taylor@email.com,(903) 686-4860,New York,IL,2022-12-05,Basic,41,9675.98
4,CUST0075,David,White,lisa.gonzalez@email.com,(921) 878-7481,San Jose,OH,2022-10-28,Standard,42,9661.74
5,CUST0101,Christopher,Johnson,jessica.williams@email.com,(366) 662-2207,Philadelphia,OH,2023-08-14,Standard,1,9619.35
6,CUST0137,Charles,Jackson,jennifer.lopez@email.com,(604) 931-1568,Phoenix,PA,2023-11-24,Premium,34,9575.63
7,CUST0009,John,Wilson,richard.taylor@email.com,(359) 308-3693,Chicago,CA,2022-08-26,Basic,25,9560.93
8,CUST0010,Lisa,Anderson,lisa.rodriguez@email.com,(660) 677-6145,New York,PA,2023-10-28,Premium,30,9540.96
9,CUST0191,John,Wilson,thomas.davis@email.com,(220) 999-1145,San Jose,PA,2022-03-06,Standard,19,9535.89

In [33]:
# Exercise 3: Customer statistics by segment
for i in df_customers['customer_segment'].unique():
    df_customer_segment = df_customers[df_customers['customer_segment'] == i]
    count = len(df_customer_segment)
    avg_value = df_customer_segment['lifetime_value'].mean()
    print(f"{i}: {count} customers, Avg lifetime value: ${avg_value:,.2f}")

Standard: 101 customers, Avg lifetime value: $5,013.19
Premium: 34 customers, Avg lifetime value: $5,202.70
Basic: 65 customers, Avg lifetime value: $4,956.41